const teams = {
  Benny: {
    1: {
      name: "Damian Lillard",
      court: "back",
    },
    2: {
      name: "Devin Booker",
      court: "back",
    },
    3: { name: "Jusuf Nurkic", court: "front" },
    4: { name: "Joe Harris", court: "back" },
    5: { name: "Josh Giddey", court: "back" },
    6: { name: "Carmelo Anthony", court: "front" },
    7: { name: "Anthony Edwards", court: "front" },
    8: { name: "JaVale McGee", court: "front" },
    9: { name: "Kyle Kuzma", court: "front" },
    10: { name: "Kent Bazemore", court: "back" },
    11: { name: "T.J. Warren", court: "front" },
    12: { name: "Larry Nance Jr.", court: "back" },
  },
  Byron: {
    1: {
      name: "Luka Doncic",
      court: "back",
    },
    2: {
      name: "LeBron James",
      court: "front",
    },
    3: { name: "Domantas Sabonis", court: "front" },
    4: { name: "LaMelo Ball", court: "back" },
    5: { name: "Ja Morant", court: "back" },
    6: { name: "Clint Capela", court: "front" },
    7: { name: "Pascal Siakam", court: "front" },
    8: { name: "Darius Garland", court: "back" },
    9: { name: "Jonathan Isaac", court: "front" },
    10: { name: "Marcus Smart", court: "back" },
    11: { name: "Patty Mills", court: "back" },
    12: { name: "Kevin Love", court: "front" },
  },
  Cail: {
    1: {
      name: "Joel Embiid",
      court: "front",
    },
    2: {
      name: "Nikola Vucevic",
      court: "front",
    },
    3: { name: "Jimmy Butler", court: "front" },
    4: { name: "Fred VanVleet", court: "back" },
    5: { name: "Malcolm Brogdon", court: "back" },
    6: { name: "DeMar DeRozan", court: "back" },
    7: { name: "Terry Rozier", court: "back" },
    8: { name: "Jalen Green", court: "back" },
    9: { name: "Richaun Holmes", court: "front" },
    10: { name: "Harrison Barnes", court: "front" },
    11: { name: "Devonte' Graham", court: "back" },
    12: { name: "Mason Plumlee", court: "front" },
  },
  Gibbo: {
    1: {
      name: "Jayson Tatum",
      court: "front",
    },
    2: {
      name: "Karl-Anthony Towns",
      court: "front",
    },
    3: { name: "Chris Paul", court: "back" },
    4: { name: "Shai Gilgeous-Alexander", court: "back" },
    5: { name: "Duncan Robinson", court: "back" },
    6: { name: "Jerami Grant", court: "front" },
    7: { name: "Caris LeVert", court: "back" },
    8: { name: "Mitchell Robinson", court: "front" },
    9: { name: "Bogdan Bogdanovic", court: "back" },
    10: { name: "Kelly Olynyk", court: "front" },
    11: { name: "Seth Curry", court: "back" },
    12: { name: "Steven Adams", court: "front" },
  },
  LB: {
    1: {
      name: "Nikola Jokic",
      court: "front",
    },
    2: {
      name: "Donovan Mitchell",
      court: "back",
    },
    3: { name: "Khris Middleton", court: "front" },
    4: { name: "John Collins", court: "front" },
    5: { name: "Jrue Holiday", court: "back" },
    6: { name: "Tobias Harris", court: "front" },
    7: { name: "Jarrett Allen", court: "front" },
    8: { name: "Klay Thompson", court: "back" },
    9: { name: "Mikal Bridges", court: "front" },
    10: { name: "Joe Ingles", court: "front" },
    11: { name: "Dennis Schroder", court: "back" },
    12: { name: "Tim Hardaway Jr.", court: "back" },
  },
  Mick: {
    1: {
      name: "James Harden",
      court: "back",
    },
    2: {
      name: "Anthony Davis",
      court: "front",
    },
    3: { name: "Ben Simmons", court: "back" },
    4: { name: "Deandre Ayton", court: "front" },
    5: { name: "Brandon Ingram", court: "front" },
    6: { name: "Lonzo Ball", court: "back" },
    7: { name: "Spencer Dinwiddie", court: "back" },
    8: { name: "Aaron Gordon", court: "front" },
    9: { name: "Evan Mobley", court: "front" },
    10: { name: "Buddy Hield", court: "back" },
    11: { name: "Evan Fournier", court: "back" },
    12: { name: "Montrezl Harrell", court: "front" },
  },
  Moir: {
    1: {
      name: "Kevin Durant",
      court: "front",
    },
    2: {
      name: "Russell Westbrook",
      court: "back",
    },
    3: { name: "Bam Adebayo", court: "front" },
    4: { name: "Kyle Lowry", court: "back" },
    5: { name: "Andrew Wiggins", court: "front" },
    6: { name: "Kyrie Irving", court: "back" },
    7: { name: "Mike Conley", court: "back" },
    8: { name: "Victor Oladipo", court: "back" },
    9: { name: "Isaiah Stewart", court: "front" },
    10: { name: "Reggie Jackson", court: "back" },
    11: { name: "Dillon Brooks", court: "front" },
    12: { name: "Miles Bridges", court: "front" },
  },
  Tex: {
    1: {
      name: "Trae Young",
      court: "back",
    },
    2: {
      name: "Paul George",
      court: "front",
    },
    3: { name: "Rudy Gobert", court: "front" },
    4: { name: "Christian Wood", court: "front" },
    5: { name: "Cade Cunningham", court: "back" },
    6: { name: "Dejounte Murray", court: "back" },
    7: { name: "OG Anunoby", court: "front" },
    8: { name: "Zion Williamson", court: "front" },
    9: { name: "Jalen Suggs", court: "back" },
    10: { name: "Myles Turner", court: "front" },
    11: { name: "Norman Powell", court: "back" },
    12: { name: "James Wiseman", court: "front" },
  },
  Trev: {
    1: {
      name: "Giannis Antetokounmpo",
      court: "front",
    },
    2: {
      name: "Zach LaVine",
      court: "back",
    },
    3: { name: "De'Aaron Fox", court: "back" },
    4: { name: "CJ McCollum", court: "back" },
    5: { name: "Jonas Valanciunas", court: "front" },
    6: { name: "Tyler Herro", court: "back" },
    7: { name: "Collin Sexton", court: "back" },
    8: { name: "Gordon Hayward", court: "front" },
    9: { name: "D'Angelo Russell", court: "back" },
    10: { name: "Kristaps Porzingis", court: "front" },
    11: { name: "Malik Beasley", court: "back" },
    12: { name: "Jordan Clarkson", court: "back" },
  },
  Scotty: {
    1: {
      name: "Stephen Curry",
      court: "back",
    },
    2: {
      name: "Bradley Beal",
      court: "back",
    },
    3: { name: "Julius Randle", court: "front" },
    4: { name: "Jaylen Brown", court: "front" },
    5: { name: "Michael Porter Jr.", court: "front" },
    6: { name: "Tyrese Haliburton", court: "back" },
    7: { name: "Draymond Green", court: "front" },
    8: { name: "RJ Barrett", court: "back" },
    9: { name: "Jaren Jackson Jr.", court: "front" },
    10: { name: "Kevin Porter Jr.", court: "back" },
    11: { name: "Mo Bamba", court: "front" },
    12: { name: "Lauri Markkanen", court: "front" },
  },
};
module.exports = { teams };
