const teams = {
  Benny: {
    player1: "Damian Lillard",
    player2: "Devin Booker",
    player3: "Jusuf Nurkić",
    player4: "Joe Harris",
    player5: "Josh Giddey",
    player6: "Carmelo Anthony",
    player7: "Anthony Edwards",
    player8: "JaVale McGee",
    player9: "Kyle Kuzma",
    player10: "Kent Bazmore",
    player11: "T.J. Warren",
    player12: "Larry Nance Jr.",
  },
  Byron: {
    player1: "Luka Dončić",
    player2: "LeBron James",
    player3: "Domantas Sabonis",
    player4: "LaMelo Ball",
    player5: "Ja Morant",
    player6: "Clint Capela",
    player7: "Pascal Siakam",
    player8: "Darius Garland",
    player9: "Jonathan Isaac",
    player10: "Marcus Smart",
    player11: "Patty Mills",
    player12: "Kevin Love"
  },
  Cail: {
    player1: "Joel Embiid",
    player2: "Nikola Vučević",
    player3: "Jimmy Butler",
    player4: "Fred VanVleet",
    player5: "Malcolm Brogdon",
    player6: "DeMar DeRozan",
    player7: "Terry Rozier",
    player8: "Jalen Green",
    player9: "Richaun Holmes",
    player10: "Harrison Barnes",
    player11: "Devonte' Graham",
    player12: "Mason Plumlee"
  },
  Gibbo: {
    player1: "Jayson Tatum",
    player2: "Karl-Anthony Towns",
    player3: "Chris Paul",
    player4: "Shai Gilgeous-Alexander",
    player5: "Duncan Robinson",
    player6: "Jerami Grant",
    player7: "Caris LeVert",
    player8: "Mitchell Robinson",
    player9: "Bogdan Bogdanović",
    player10: "Kelly Olynyk",
    player11: "Seth Curry",
    player12: "Steven Adams"
  },
  LB: {
    player1: "Nikola Jokić",
    player2: "Donovan Mitchell",
    player3: "Khris Middleton",
    player4: "John Collins",
    player5: "Jrue Holiday",
    player6: "Tobias Harris",
    player7: "Jarrett Allen",
    player8: "Klay Thompson",
    player9: "Mikal Bridges",
    player10: "Joe Ingles",
    player11: "Dennis Schröder",
    player12: "Tim Hardaway Jr."
  },
  Mick: {
    player1: "James Harden",
    player2: "Anthony Davis",
    player3: "Ben Simmons",
    player4: "Deandre Ayton",
    player5: "Brandon Ingram",
    player6: "Lonzo Ball",
    player7: "Spencer Dinwiddie",
    player8: "Aaron Gordon",
    player9: "Evan Mobley",
    player10: "Buddy Hield",
    player11: "Evan Fournier",
    player12: "Montrezl Harrell"
  },
  Moir: {
    player1: "Kevin Durant",
    player2: "Russell Westbrook",
    player3: "Bam Adebayo",
    player4: "Kyle Lowry",
    player5: "Andrew Wiggins",
    player6: "Kyrie Irving",
    player7: "Mike Conley",
    player8: "Victor Oladipo",
    player9: "Isaiah Stewart",
    player10: "Reggie Jackson",
    player11: "Dillon Brooks",
    player12: "Miles Bridges"
  },
  Scotty: {
    player1: "Stephen Curry",
    player2: "Bradley Beal",
    player3: "Julius Randle",
    player4: "Jaylen Brown",
    player5: "Michael Porter Jr.",
    player6: "Tyrese Haliburton",
    player7: "Draymond Green",
    player8: "RJ Barrett",
    player9: "Jaren Jackson Jr.",
    player10: "Kevin Porter Jr.",
    player11: "Mo Bamba",
    player12: "Lauri Markkanen"
  },
  Tex: {
    player1: "Trae Young",
    player2: "Paul George",
    player3: "Rudy Gobert",
    player4: "Christian Wood",
    player5: "Cade Cunningham",
    player6: "Dejounte Murray",
    player7: "OG Anunoby",
    player8: "Zion Williamson",
    player9: "Jalen Suggs",
    player10: "Myles Turner",
    player11: "Norman Powell",
    player12: "James Wiseman"
  },
  Trev: {
    player1: "Giannis Antetokounmpo",
    player2: "Zach LaVine",
    player3: "De'Aaron Fox",
    player4: "CJ McCollum",
    player5: "Jonas Valančiūnas",
    player6: "Tyler Herro",
    player7: "Collin Sexton",
    player8: "Gordon Hayward",
    player9: "D'Angelo Russell",
    player10: "Kristaps Porziņģis",
    player11: "Malik Beasley",
    player12: "Jordan Clarkson"
  },
};
module.exports = { teams };
