const teams = {
  Benny: {
    player: {
      1: "Damian Lillard",
      2: "Devin Booker",
      3: "Jusuf Nurkić",
      4: "Joe Harris",
      5: "Josh Giddey",
      6: "Carmelo Anthony",
      7: "Anthony Edwards",
      8: "JaVale McGee",
      9: "Kyle Kuzma",
      10: "Kent Bazemore",
      11: "T.J. Warren",
      12: "Larry Nance Jr.",
    },
  },
  Byron: {
    player: {
      1: "Luka Dončić",
      2: "LeBron James",
      3: "Domantas Sabonis",
      4: "LaMelo Ball",
      5: "Ja Morant",
      6: "Clint Capela",
      7: "Pascal Siakam",
      8: "Darius Garland",
      9: "Jonathan Isaac",
      10: "Marcus Smart",
      11: "Patty Mills",
      12: "Kevin Love",
    },
  },
  Cail: {
    player: {
      1: "Joel Embiid",
      2: "Nikola Vučević",
      3: "Jimmy Butler",
      4: "Fred VanVleet",
      5: "Malcolm Brogdon",
      6: "DeMar DeRozan",
      7: "Terry Rozier",
      8: "Jalen Green",
      9: "Richaun Holmes",
      10: "Harrison Barnes",
      11: "Devonte' Graham",
      12: "Mason Plumlee",
    },
  },
  Gibbo: {
    player: {
      1: "Jayson Tatum",
      2: "Karl-Anthony Towns",
      3: "Chris Paul",
      4: "Shai Gilgeous-Alexander",
      5: "Duncan Robinson",
      6: "Jerami Grant",
      7: "Caris LeVert",
      8: "Mitchell Robinson",
      9: "Bogdan Bogdanović",
      10: "Kelly Olynyk",
      11: "Seth Curry",
      12: "Steven Adams",
    },
  },
  LB: {
    player: {
      1: "Nikola Jokić",
      2: "Donovan Mitchell",
      3: "Khris Middleton",
      4: "John Collins",
      5: "Jrue Holiday",
      6: "Tobias Harris",
      7: "Jarrett Allen",
      8: "Klay Thompson",
      9: "Mikal Bridges",
      10: "Joe Ingles",
      11: "Dennis Schröder",
      12: "Tim Hardaway Jr.",
    },
  },
  Mick: {
    player: {
      1: "James Harden",
      2: "Anthony Davis",
      3: "Ben Simmons",
      4: "Deandre Ayton",
      5: "Brandon Ingram",
      6: "Lonzo Ball",
      7: "Spencer Dinwiddie",
      8: "Aaron Gordon",
      9: "Evan Mobley",
      10: "Buddy Hield",
      11: "Evan Fournier",
      12: "Montrezl Harrell",
    },
  },
  Moir: {
    player: {
      1: "Kevin Durant",
      2: "Russell Westbrook",
      3: "Bam Adebayo",
      4: "Kyle Lowry",
      5: "Andrew Wiggins",
      6: "Kyrie Irving",
      7: "Mike Conley",
      8: "Victor Oladipo",
      9: "Isaiah Stewart",
      10: "Reggie Jackson",
      11: "Dillon Brooks",
      12: "Miles Bridges",
    },
  },
  Scotty: {
    player: {
      1: "Stephen Curry",
      2: "Bradley Beal",
      3: "Julius Randle",
      4: "Jaylen Brown",
      5: "Michael Porter Jr.",
      6: "Tyrese Haliburton",
      7: "Draymond Green",
      8: "RJ Barrett",
      9: "Jaren Jackson Jr.",
      10: "Kevin Porter Jr.",
      11: "Mo Bamba",
      12: "Lauri Markkanen",
    },
  },
  Tex: {
    player: {
      1: "Trae Young",
      2: "Paul George",
      3: "Rudy Gobert",
      4: "Christian Wood",
      5: "Cade Cunningham",
      6: "Dejounte Murray",
      7: "OG Anunoby",
      8: "Zion Williamson",
      9: "Jalen Suggs",
      10: "Myles Turner",
      11: "Norman Powell",
      12: "James Wiseman",
    },
  },
  Trev: {
    player: {
      1: "Giannis Antetokounmpo",
      2: "Zach LaVine",
      3: "De'Aaron Fox",
      4: "CJ McCollum",
      5: "Jonas Valančiūnas",
      6: "Tyler Herro",
      7: "Collin Sexton",
      8: "Gordon Hayward",
      9: "D'Angelo Russell",
      10: "Kristaps Porziņģis",
      11: "Malik Beasley",
      12: "Jordan Clarkson",
    },
  },
};
module.exports = { teams };
